instrumentation:
  root: ./src
  excludes: [
    "server/start.js",
    "server/dev.js",
    "client/app.js",
    "client/reducers/index.js",
    "client/store.js",
    "client/history.js",
    "client/components/upload_photo_btn.js",
    "client/components/upload_photo.js"
  ]
  include-all-sources: true
check:
  global:
    branches   : 89
    functions  : 89
    lines      : 89
    statements : 89
