instrumentation:
  root: ./src
  excludes: [
    "server/start.js",
    "client/app.js",
    "client/reducers/index.js",
    "client/store.js",
    "client/components/upload_photo_btn.js",
    "client/containers/mood_monitor.js"
    # mode monitor will be changed later(to add states and more)
  ]
  include-all-sources: true
check:
  global:
    branches   : 100
    functions  : 100
    lines      : 100
    statements : 100
