language: node_js
node_js:
  - "7"
addons:
  postgresql: '9.4'
env:
  export DB_USER=postgres
  DB_PASS=
  DB_URL='postgres://postgres:@localhost:5432/near_miss_test'
before_install:
  - psql -U postgres near_miss_test < ./src/server/model/queries/schema.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
