export const SET_PHOTO = 'SET_PHOTO'
export const SET_NAME = 'SET_NAME'
export const SET_SITE = 'SET_SITE'
export const RESET_SITE = 'RESET_SITE'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_DESCRIPTION = 'SET_DESCRIPTION'
export const SET_REPORT_TYPE = 'SET_REPORT_TYPE'

export const SET_POSTING = 'SET_POSTING'
export const SET_POST_RESULT = 'SET_POST_RESULT'
